In [1]:
#Using rank,trace,det,eigen values approach
import numpy as np
import cv2
import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB


In [2]:
def to_real(v):
    return (np.sqrt(np.real(v)*2+np.imag(v)*2))
def calculate_metrics(cm):
    num_classes = cm.shape[0]
    metrics = {}

    for class_idx in range(num_classes):
        true_positives = cm[class_idx, class_idx]
        false_positives = np.sum(cm[:, class_idx]) - true_positives
        false_negatives = np.sum(cm[class_idx, :]) - true_positives
        total_samples = np.sum(cm)
        true_negatives = total_samples-sum([true_positives,false_negatives,false_positives])

        precision = true_positives / (true_positives + false_positives)
        accuracy = true_positives / np.sum(cm[class_idx, :])
        specificity = np.sum(true_positives / (true_positives + false_negatives)) / num_classes
        sensitivity = np.sum(true_negatives / (true_negatives + false_positives)) / num_classes
        balanced_accuracy = (specificity + sensitivity) / 2
        f_score = 2 * (precision * sensitivity) / (precision + sensitivity)

        metrics[class_idx] = {
            'Precision': precision,
            'Accuracy': accuracy,
            'Specificity': specificity,
            'Sensitivity': sensitivity,
            'Balanced Accuracy': balanced_accuracy,
            'F-Score': f_score
        }

    for class_idx, metrics in metrics.items():
        print(f"Metrics for Class {class_idx}:")
        for metric, value in metrics.items():
            print(f"{metric}: {value}")    
        print()
# calculate_metrics(cm)

In [3]:
def to_real(v):
    return (np.sqrt(np.real(v)**2+np.imag(v)**2))


In [4]:
directory=r"C:/Users/HP/Desktop/Brandnew_CBP/Dataset/bg_removed"
directory=r"C:/Users/HP/Desktop/Brandnew_CBP/Dataset/bg_removed"
shape=(25,25)
def join(s1,s2):
    return s1+'/'+s2

In [5]:
train_data=[]
for i in os.listdir(directory):
    path=join(directory,i)
    for img in os.listdir(path): 
        features=[]
        array_image=cv2.imread(join(path,img),cv2.IMREAD_GRAYSCALE)
        features.append(to_real(np.linalg.matrix_rank(array_image)))
        features.append(np.linalg.det(array_image))
        features.append(to_real(array_image.trace()))
        value,vector=np.linalg.eig(array_image)
        for val in value:
            features.append(to_real(val))
        features.append(i[-2:])
        train_data.append(features)
train_df=pd.DataFrame(train_data)
train_df.head(20)


0             1       2            3           4           5    
0   25.0  1.157707e+40  2455.0  2675.330211  256.187358  156.529563  \
1   25.0 -6.510908e+43  2396.0  2358.648943  246.824103  246.824103   
2   25.0  1.213114e+49  1439.0  1113.775538  244.828178  235.534748   
3   25.0 -2.910781e+42  2121.0  2235.444069  222.091255  189.697692   
4   25.0  2.374932e+45  2006.0  2175.404032  207.622503  207.622503   
5   25.0 -1.248735e+43  2118.0  2331.282158  217.628836  163.455679   
6   25.0 -5.961149e+47  1564.0  1366.384190  272.194078  272.194078   
7   25.0  1.482070e+42  2125.0  2232.376621  272.033965  263.682683   
8   25.0 -6.168679e+41  2266.0  2275.336747  236.372886  196.944465   
9   25.0  8.945994e+41  2129.0  2125.485930  253.714654  231.114620   
10  25.0 -3.568520e+39  2218.0  2268.672125  260.746370  131.762859   
11  25.0  1.410960e+41  2224.0  2293.918363  200.766048  184.771971   
12  25.0  6.055322e+41  2238.0  2221.596158  268.426049  254.496346   
13  25.0 -1.132053e+40  2229.0  2312.814587  221.665041  146.378308   
14  25.0 -7.804096e+41  2194.0  2326.830046  187.161064  133.201986   
15  25.0 -7.541692e+42  2396.0  2298.091598  261.540107  245.531301   
16  25.0 -1.843343e+49  1954.0  1664.550402  260.091811  188.968997   
17  25.0  2.997581e+41  2221.0  2278.261854  234.669029  171.181743   
18  25.0  2.147557e+48  1693.0  1453.617129  286.918731  286.918731   
19  25.0  1.896617e+50  1582.0  1483.807055  308.735005  308.735005   

            6           7           8           9   ...          19   
0   156.212350  113.510585   83.801327   83.801327  ...   30.704653  \
1   229.506189  121.169360  121.169360  108.979216  ...   45.154343   
2   235.534748  203.241269  203.241269  161.932486  ...  108.440678   
3   155.764128  136.868939  136.868939  102.806535  ...   34.758838   
4   157.792412  122.944338  122.944338  105.090022  ...   40.875028   
5   163.455679  148.771066  110.594236  110.594236  ...   27.351595   
6   167.805041  165.140931  165.140931  174.045795  ...   65.456749   
7   126.992869  126.992869   96.912609   96.912609  ...   44.843245   
8   141.628620  141.628620  110.195883  110.195883  ...   37.950640   
9   129.237386  129.237386  131.709422   89.425359  ...   39.275591   
10  131.762859  135.373212  112.624644  112.624644  ...   29.889008   
11  146.000260  105.015672  105.015672  104.633818  ...   29.738567   
12  134.974793  134.974793  119.708267  100.453936  ...   29.878250   
13  108.595751  117.796102  117.796102  100.511175  ...   26.929534   
14  133.201986  149.091411  103.343411  103.343411  ...   26.227067   
15  132.483119  102.146668  102.146668  111.482083  ...   18.970393   
16  188.968997  173.718313  171.811863  171.811863  ...   55.722351   
17  171.181743  133.534245  133.534245  121.419321  ...   30.318530   
18  222.994132  157.044855  145.252761  145.252761  ...   68.775583   
19  265.238588  190.940272  190.940272  149.438861  ...   86.086934   

           20         21         22         23         24         25   
0   30.704653  26.384689  16.116345   9.345468   9.345468   5.894071  \
1   41.935529  29.211777  24.929181  24.929181  13.017942  13.017942   
2   46.013636  46.013636  48.428437  48.428437  31.774565  13.734643   
3   23.812113  18.702601  18.702601  13.611175  13.611175  11.412062   
4   28.257268  28.257268  23.407649  23.407649  28.270462  19.211045   
5   29.924588  29.924588  25.726266  25.726266  21.844335  21.844335   
6   61.500326  67.538501  43.527567  30.244101  30.244101  10.152936   
7   20.011470  20.011470  23.357231  23.357231  14.882290  14.882290   
8   36.648648  36.648648  32.936531  16.001030  12.749229  12.749229   
9   39.237158  20.962035  20.962035  20.590701   7.532826   7.532826   
10  29.769763  14.895680  14.895680   8.848195   7.154599   7.154599   
11  29.738567  26.230850  26.230850  10.113967  10.113967   4.235623   
12  24.478321  13.900456  13.900456  17.358381  17.358381   3.227093   
13  26.929534 

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,y_train=train_df.iloc[:,:-1],train_df.iloc[:,-1]
sc=MinMaxScaler()
X_train=sc.fit_transform(X_train)
pd.DataFrame(X_train)


0         1         2         3         4         5         6    
0     1.0  0.698868  1.000000  1.000000  0.110350  0.395799  0.460935  \
1     1.0  0.698868  0.973351  0.881629  0.105372  0.717667  0.731553   
2     1.0  0.699965  0.541102  0.416313  0.104311  0.677425  0.753812   
3     1.0  0.698868  0.849142  0.835577  0.092223  0.514032  0.459280   
4     1.0  0.698868  0.797200  0.813135  0.084531  0.577927  0.466769   
...   ...       ...       ...       ...       ...       ...       ...   
2179  1.0  0.698879  0.195122  0.345154  0.087337  0.596739  0.682693   
2180  1.0  0.698887  0.193767  0.320453  0.085977  0.492681  0.556527   
2181  1.0  0.698840  0.207317  0.322047  0.081980  0.485934  0.555468   
2182  1.0  0.698880  0.204607  0.328043  0.082791  0.506223  0.576483   
2183  1.0  0.698867  0.200542  0.312672  0.080509  0.411426  0.425740   

            7         8         9   ...        18        19        20   
0     0.354735  0.303722  0.329776  ...  0.273772  0.229950  0.258886  \
1     0.385777  0.474377  0.454623  ...  0.338166  0.338166  0.353579   
2     0.718424  0.849189  0.717198  ...  0.812124  0.812124  0.387963   
3     0.449409  0.546075  0.424015  ...  0.344770  0.260313  0.200771   
4     0.392972  0.482483  0.435338  ...  0.306117  0.306117  0.238251   
...        ...       ...       ...  ...       ...       ...       ...   
2179  0.577319  0.611434  0.591555  ...  0.460515  0.460515  0.429528   
2180  0.632745  0.547926  0.594926  ...  0.578807  0.456968  0.371496   
2181  0.524441  0.564009  0.612389  ...  0.484014  0.444408  0.500329   
2182  0.438392  0.533661  0.521521  ...  0.401528  0.401528  0.420559   
2183  0.489175  0.506217  0.549640  ...  0.340016  0.340016  0.490899   

            21        22        23        24        25        26        27  
0     0.255778  0.176453  0.105128  0.091723  0.057849  0.038969  0.001219  
1     0.283184  0.272943  0.280431  0.127768  0.127768  0.009105  0.034768  
2     0.446064  0.530229  0.544777  0.311859  0.134802  0.109345  0.082848  
3     0.181306  0.204770  0.153114  0.133590  0.112006  0.057912  0.039826  
4     0.273931  0.256284  0.263315  0.277467  0.188551  0.213213  0.072804  
...        ...       ...       ...       ...       ...       ...       ...  
2179  0.493854  0.690188  0.302187  0.303892  0.303892  0.342205  0.022803  
2180  0.427130  0.407165  0.251664  0.219574  0.136541  0.412345  0.173313  
2181  0.415050  0.468763  0.297458  0.086724  0.192313  0.244026  0.320573  
2182  0.483541  0.613509  0.589329  0.514184  0.029345  0.239328  0.181333  
2183  0.564415  0.521142  0.350629  0.305921  0.264903  0.336134  0.002127  

[2184 rows x 28 columns]

In [7]:
df=pd.read_csv("C:/Users/HP/Desktop/Brandnew_CBP/Dataset/c2.csv")#train
tdf=pd.read_csv("C:/Users/HP/Desktop/Brandnew_CBP/Dataset/testf.csv")#test

In [8]:
X_train, X_test, y_train, y_test = df.iloc[:,:-1],tdf.iloc[:,:-1],df.iloc[:,-1],tdf.iloc[:,-1]


In [12]:
#Stratified k-fold with RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier




# Classifier
clf = RandomForestClassifier()

#number of folds
n_splits = 5
best_acc=0
# Initialize the Stratified K-Fold cross-validator
skf = StratifiedKFold(n_splits=n_splits)

best_train,best_test=None,None
for fold, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    print(f"Fold {fold + 1}")
    
    # Spliting the data into training and testing sets for this fold
    X_train_fold, X_test_fold = X_train.iloc[train_index,:], X_train.iloc[test_index,:]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]
    
    # Fitting the  training data
    clf.fit(X_train_fold, y_train_fold)
    
    # predictioning on the testing data
    y_pred = clf.predict(X_test_fold)
    
    # confusion matrix
    cm = confusion_matrix(y_test_fold, y_pred)
    print(cm)
    acc=accuracy_score(y_pred,y_test_fold)*100
    if acc>best_acc:
        best_train=train_index
        best_test=test_index
        best_acc=acc
    print(acc)
 



Fold 1
[[20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  

In [10]:
X_train_best, X_test_best = X_train.iloc[best_train,:], X_train.iloc[best_test,:]
y_train_best, y_test_best = y_train.iloc[best_train], y_train.iloc[best_test]
clf.fit(X_train_best,y_train_best)
y_pred_best=clf.predict(X_test_best)
cm=confusion_matrix(y_test_best,y_pred_best)
print("accuracy score",accuracy_score(y_test_best,y_pred_best))
calculate_metrics(cm)


accuracy score 0.9954233409610984
Metrics for Class 0:
Precision: 1.0
Accuracy: 1.0
Specificity: 0.045454545454545456
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.045454545454545456
F-Score: 0.08695652173913045

Metrics for Class 1:
Precision: 1.0
Accuracy: 1.0
Specificity: 0.045454545454545456
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.045454545454545456
F-Score: 0.08695652173913045

Metrics for Class 2:
Precision: 1.0
Accuracy: 1.0
Specificity: 0.045454545454545456
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.045454545454545456
F-Score: 0.08695652173913045

Metrics for Class 3:
Precision: 1.0
Accuracy: 1.0
Specificity: 0.045454545454545456
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.045454545454545456
F-Score: 0.08695652173913045

Metrics for Class 4:
Precision: 1.0
Accuracy: 1.0
Specificity: 0.045454545454545456
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.045454545454545456
F-Score: 0.08695652173913045

Metrics for Class 5:
Preci

In [11]:
y_pred_test=clf.predict(X_test)
print("accuracy score",accuracy_score(y_test,y_pred_test))
cm=confusion_matrix(y_test,y_pred_test)
calculate_metrics(cm)

accuracy score 0.07537688442211055
Metrics for Class 0:
Precision: 1.0
Accuracy: 0.7
Specificity: 0.031818181818181815
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.038636363636363635
F-Score: 0.08695652173913045

Metrics for Class 1:
Precision: nan
Accuracy: 0.0
Specificity: 0.0
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.022727272727272728
F-Score: nan

Metrics for Class 2:
Precision: nan
Accuracy: 0.0
Specificity: 0.0
Sensitivity: 0.045454545454545456
Balanced Accuracy: 0.022727272727272728
F-Score: nan

Metrics for Class 3:
Precision: 0.0
Accuracy: 0.0
Specificity: 0.0
Sensitivity: 0.03823953823953824
Balanced Accuracy: 0.01911976911976912
F-Score: 0.0

Metrics for Class 4:
Precision: 0.75
Accuracy: 0.3
Specificity: 0.013636363636363636
Sensitivity: 0.04521404521404521
Balanced Accuracy: 0.029425204425204424
F-Score: 0.08528655678209587

Metrics for Class 5:
Precision: 0.0
Accuracy: 0.0
Specificity: 0.0
Sensitivity: 0.043771043771043766
Balanced Accuracy: 0.0218

C:\Users\HP\AppData\Local\Temp\ipykernel_16656\4291859585.py:14: RuntimeWarning: invalid value encountered in longlong_scalars
  precision = true_positives / (true_positives + false_positives)
C:\Users\HP\AppData\Local\Temp\ipykernel_16656\4291859585.py:15: RuntimeWarning: invalid value encountered in longlong_scalars
  accuracy = true_positives / np.sum(cm[class_idx, :])
C:\Users\HP\AppData\Local\Temp\ipykernel_16656\4291859585.py:16: RuntimeWarning: invalid value encountered in longlong_scalars
  specificity = np.sum(true_positives / (true_positives + false_negatives)) / num_classes
